[build]
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"
  functions = ".netlify/functions"

# Strict CSP for statsdev page only
[[headers]]
  for = "/statsdev.html"
  [headers.values]
    # Keep scripts/styles strict for React app
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'nonce-{random}'; connect-src 'self' https://api.kraken.com wss://ws.kraken.com https://generativelanguage.googleapis.com https://*.googleapis.com https://api.openai.com; img-src 'self' data: https:; style-src 'self' 'nonce-{random}' https://fonts.googleapis.com https://fonts.gstatic.com; font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com; frame-ancestors 'none'; object-src 'none'; base-uri 'self'; form-action 'self'" # Stats dev CSP
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    X-Content-Type-Options = "nosniff"

# Relaxed CSP for main pricing page
[[headers]]
  for = "/"
  [headers.values]
    # Allow inline styles and scripts for pricing page
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self' https://api.kraken.com wss://ws.kraken.com https://generativelanguage.googleapis.com https://*.googleapis.com https://api.openai.com; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com; font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com; frame-ancestors 'none'; object-src 'none'; base-uri 'self'; form-action 'self'" # Main pricing page CSP
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

# Relaxed CSP for test pages only
[[headers]]
  for = "/test-db-connection.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self' https://api.kraken.com wss://ws.kraken.com https://generativelanguage.googleapis.com https://*.googleapis.com https://api.openai.com; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com; font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com; frame-ancestors 'none'; object-src 'none'; base-uri 'self'; form-action 'self'" # Test page CSP
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/statsdev.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://esm.run; connect-src 'self' https://api.kraken.com wss://ws.kraken.com https://www.alphavantage.co https://generativelanguage.googleapis.com; img-src 'self' data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com https://esm.run; font-src 'self' https://fonts.gstatic.com" # Stats dev page CSP
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    X-Content-Type-Options = "nosniff"

# Proxy any /api/* calls to Netlify Functions (not used now, but handy later)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# =====================================================
# HOURLY SNAPSHOTS COLLECTION - v1.5
# =====================================================
# Note: Scheduled functions will be configured via Netlify Dashboard
# Manual trigger available at: /trigger-hourly-collection

# Alternative: Manual trigger endpoint for testing
[[redirects]]
  from = "/trigger-hourly-collection"
  to = "/.netlify/functions/hourly-collector"
  status = 200